name=input("Enter your name: ")
product=input("Enter the product name: ")
print("Name: {}, Product: {}".format(name, product))
print("Hello {}! The price of {} is $100.".format(name, product))
print(name.ljust(20))
print(name.rjust(20))
print(name.center(20))
print(product.ljust(20))
print(product.rjust(20))
print(product.center(20))